# Generated by Django 4.2.15 on 2026-04-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_shippingtracking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingupdate',
            name='tracking',
        ),
        migrations.DeleteModel(
            name='ShippingTracking',
        ),
        migrations.DeleteModel(
            name='ShippingUpdate',
        ),
    ]
