# Generated by Django 4.2.15 on 2026-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_shippingupdate_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, help_text='Estimated delivery date (excluding weekends)', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_tracking',
            field=models.CharField(blank=True, help_text='Shipping tracking number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_update',
            field=models.TextField(blank=True, help_text='Shipping status updates'),
        ),
    ]
