# Generated by Django 4.2.15 on 2026-06-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('Black', 'Black'), ('Jet Black', 'Jet Black'), ('White', 'White'), ('Silver', 'Silver'), ('Space Gray', 'Space Gray'), ('Gold', 'Gold'), ('Rose Gold', 'Rose Gold'), ('Red', 'Red (Product RED)'), ('Blue', 'Blue'), ('Purple', 'Purple'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Coral', 'Coral'), ('Pacific Blue', 'Pacific Blue'), ('Graphite', 'Graphite'), ('Sierra Blue', 'Sierra Blue'), ('Alpine Green', 'Alpine Green'), ('Deep Purple', 'Deep Purple'), ('Starlight', 'Starlight'), ('Midnight', 'Midnight'), ('Midnight Green', 'Midnight Green'), ('Pink', 'Pink'), ('Light Blue', 'Light Blue'), ('Dark Cherry', 'Dark Cherry'), ('Titanium', 'Titanium'), ('Natural Titanium', 'Natural Titanium'), ('Blue Titanium', 'Blue Titanium'), ('White Titanium', 'White Titanium'), ('Black Titanium', 'Black Titanium'), ('Desert Titanium', 'Desert Titanium'), ('Space Black', 'Space Black'), ('Teal', 'Teal'), ('Ultramarine', 'Ultramarine')], max_length=50, unique=True),
        ),
    ]
