# Generated by Django 4.2.15 on 2026-06-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphonemodel',
            name='name',
            field=models.CharField(choices=[('iPhone 12 mini', 'iPhone 12 mini'), ('iPhone 12', 'iPhone 12'), ('iPhone 12 Pro', 'iPhone 12 Pro'), ('iPhone 12 Pro Max', 'iPhone 12 Pro Max'), ('iPhone 13 mini', 'iPhone 13 mini'), ('iPhone 13', 'iPhone 13'), ('iPhone 13 Pro', 'iPhone 13 Pro'), ('iPhone 13 Pro Max', 'iPhone 13 Pro Max'), ('iPhone SE (3rd gen)', 'iPhone SE (3rd gen)'), ('iPhone 14', 'iPhone 14'), ('iPhone 14 Plus', 'iPhone 14 Plus'), ('iPhone 14 Pro', 'iPhone 14 Pro'), ('iPhone 14 Pro Max', 'iPhone 14 Pro Max'), ('iPhone 15', 'iPhone 15'), ('iPhone 15 Plus', 'iPhone 15 Plus'), ('iPhone 15 Pro', 'iPhone 15 Pro'), ('iPhone 15 Pro Max', 'iPhone 15 Pro Max'), ('iPhone 16', 'iPhone 16'), ('iPhone 16 Plus', 'iPhone 16 Plus'), ('iPhone 16 Pro', 'iPhone 16 Pro'), ('iPhone 16 Pro Max', 'iPhone 16 Pro Max')], max_length=50, unique=True),
        ),
    ]
