# Generated by Django 4.2.7 on 2026-06-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_iphonemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphonemodel',
            name='name',
            field=models.CharField(choices=[('iPhone 12 Pro', 'iPhone 12 Pro'), ('iPhone 12 Pro Max', 'iPhone 12 Pro Max'), ('iPhone 13 mini', 'iPhone 13 mini'), ('iPhone 13', 'iPhone 13'), ('iPhone 13 Pro', 'iPhone 13 Pro'), ('iPhone 13 Pro Max', 'iPhone 13 Pro Max'), ('iPhone 14', 'iPhone 14'), ('iPhone 14 Plus', 'iPhone 14 Plus'), ('iPhone 14 Pro', 'iPhone 14 Pro'), ('iPhone 14 Pro Max', 'iPhone 14 Pro Max'), ('iPhone 16', 'iPhone 16'), ('iPhone 16 Plus', 'iPhone 16 Plus')], max_length=50, unique=True),
        ),
    ]
