"""
Django settings for iphonestore project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^y^zrsl4y!vkb8%5$lonqh%ots2*wrqt#t-6w@o^pm88=mt#7^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.10.21.240', '127.0.0.1','10.10.19.163','10.10.23.58', 'localhost', '*', 'beb5-102-132-150-131.ngrok-free.app', 'd217-102-132-150-131.ngrok-free.app']

# CSRF Trusted Origins for ngrok
CSRF_TRUSTED_ORIGINS = ['https://d217-102-132-150-131.ngrok-free.app', 'https://beb5-102-132-150-131.ngrok-free.app']

# Authentication settings
LOGIN_URL = 'store:login'
LOGIN_REDIRECT_URL = 'store:home'
LOGOUT_REDIRECT_URL = 'store:home'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iphonestore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iphonestore.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Manual EFT / proof of payment instructions
# ==========================================
# Update these values with the store's real banking and contact details.
ORDER_PAYMENT_BANK_NAME = 'Tyebank'
ORDER_PAYMENT_ACCOUNT_NAME = 'iPhone Store'
ORDER_PAYMENT_ACCOUNT_NUMBER = '5106 0564 069'
ORDER_PAYMENT_BRANCH_CODE = '678910'
ORDER_PAYMENT_ACCOUNT_TYPE = 'Current Account'
ORDER_PAYMENT_PROOF_EMAIL = 'iphonestorequaries@gmail.com'
ORDER_PAYMENT_WHATSAPP = '0688833737'

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_TIMEOUT = 8
EMAIL_HOST_USER = 'iphonestorequaries@gmail.com'
EMAIL_HOST_PASSWORD = 'sykyclljoaxbednp'
DEFAULT_FROM_EMAIL = 'iPhone Store <iphonestorequaries@gmail.com>'

# Render blocks SMTP ports on many services. Use Brevo's HTTPS API when this is set.
BREVO_API_KEY = os.environ.get('BREVO_API_KEY', '').strip()
BREVO_SENDER_EMAIL = os.environ.get('BREVO_SENDER_EMAIL', ORDER_PAYMENT_PROOF_EMAIL).strip()
BREVO_SENDER_NAME = os.environ.get('BREVO_SENDER_NAME', 'iPhone Store').strip()


# PayFast Payment Gateway Configuration
# =====================================
# Mode: 'sandbox' for testing, 'live' for production
PAYFAST_MODE = 'live'

# Merchant Credentials (Replace with your actual PayFast credentials)
# Get these from your PayFast account dashboard
PAYFAST_MERCHANT_ID = '34493313'  # Live merchant ID
PAYFAST_MERCHANT_KEY = 'wfr3ovxbihvsv'  # Live merchant key

# Optional: Passphrase for additional security (set in PayFast account settings)
PAYFAST_PASSPHRASE = ''  # Leave empty if not configured


# Paystack Payment Gateway Configuration
# =====================================
# Mode: 'test' for testing, 'live' for production
PAYSTACK_MODE = 'test'

# Paystack API Keys
PAYSTACK_SECRET_KEY = 'sk_test_2a052e3d0b7334fd4a73d1f1e3d791caa88e1423'
PAYSTACK_PUBLIC_KEY = 'pk_test_c910d03f5c456fc362374fc5f45408a544e74731'

# Paystack URLs
PAYSTACK_PAYMENT_URL = 'https://api.paystack.co/transaction/initialize'
